### ISSUE TITLE
template rule for blackening

### ISSUE THREAD

**Issue by csae8092** [emt-project/emt-static#10]
e.g. 
```xml
So ist <seg type="blackening">ent</seg> mein Keiser
```

everyting in `<ent>asdf</ent>` should be rendered crossed out

something like 
```css
.blackening {
    text-decoration: line-through;
}
```
